version: '3.8'
services:
    publisher:
        image: publisher
        environment: 
            - apiPath=http://api:3333
        ports:
            - '3334:3334'
    api:
        image: api
        ports:
            - '3333:3333'
    triage:
        image: triage
        ports:
            - '3335:3335'
