{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app: {{ include "app.name" . }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- include "app.tplValue" (dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hostname }}
    - host: {{ .Values.ingress.hostname }}
      http: &hostname
        paths:
        {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ .service | default (include "app.name" $) }}
                port:
                  {{- if eq "string" (printf "%T" .port) }}
                  name: {{ .port | default "http" }}
                  {{- else }}
                  number: {{ .port | default 80 }}
                  {{- end }}
        {{- end }}
    {{- end }}
{{- end }}
