replicaCount: 2

imagePullSecrets:
  - name: acr-secret

service:
  http:
    enabled: true
    port: 80
  https:
    enabled: true
    port: 443
  type: LoadBalancer


resources: 
   limits:
     cpu: 500m
     memory: 512Mi
   requests:
     cpu: 300m
     memory: 256Mi

app:
  containerPort: 8200
