replicaCount: 2

imagePullSecrets:
  - name: acr-secret

service:
  http:
    enabled: true
    port: 80
  https:
    enabled: true
    port: 443
  type: LoadBalancer


resources: 
   limits:
     cpu: 500m
     memory: 512Mi
   requests:
     cpu: 300m
     memory: 256Mi

app:
  containerPort: 3334
 
env:
  CHECK_API_URL: https://check-api.checkmedia.org/api/graphql
  CHECK_API_TEAM: undp
  CHECK_FOLDER_ID: "11058"
  WP_URL: https://iverify.org.zm
  WP_USERNAME: chiodi
  WP_PUBLISHED_FOLDER: 8159
  NODE_TLS_REJECT_UNAUTHORIZED: 0
  DETOXIFY_TRESHOLD: 0.6

secret: 
  - name: CT_API_KEY
    secret_name: iverify
    secret_key: CT_API_KEY
  - name: CHECK_API_TOKEN
    secret_name: iverify
    secret_key: CHECK_API_TOKEN
  - name: WP_PASSWORD
    secret_name: iverify
    secret_key: WP_PASSWORD

